const API='https://api.pinterest.com/v5', OAUTH='https://www.pinterest.com/oauth/', TOKEN='https://api.pinterest.com/v5/oauth/token';
const now=()=>Math.floor(Date.now()/1000), uid=()=>crypto.randomUUID();
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json'}});
const base=(e)=>e.APP_BASE_URL.replace(/\/$/,'');
function b64(b){let s='';for(const x of new Uint8Array(b))s+=String.fromCharCode(x);return btoa(s)}function ub64(s){let x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function key(s){return crypto.subtle.importKey('raw',ub64(s),{name:'AES-GCM'},false,['encrypt','decrypt'])}async function enc(s,t){let k=await key(s),iv=crypto.getRandomValues(new Uint8Array(12)),d=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(t));return b64(iv)+'.'+b64(d)}async function dec(s,v){let [i,d]=v.split('.'),p=await crypto.subtle.decrypt({name:'AES-GCM',iv:ub64(i)},await key(s),ub64(d));return new TextDecoder().decode(p)}
function reqEnv(e){for(const k of ['PINTEREST_CLIENT_ID','PINTEREST_CLIENT_SECRET','TOKEN_ENCRYPTION_KEY'])if(!e[k])throw Error('Missing '+k)}
async function pf(token,path,opt={}){let r=await fetch(API+path,{...opt,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})}}),t=await r.text(),d={};try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok){let x=Error(d.message||d.error||'Pinterest API '+r.status);x.status=r.status;throw x}return d}
async function token(e,a){let access=a.access_token_enc?await dec(e.TOKEN_ENCRYPTION_KEY,a.access_token_enc):null;if(access&&a.access_token_expires_at>now()+300)return access;if(!a.refresh_token_enc)throw Error('Account not connected');let refresh=await dec(e.TOKEN_ENCRYPTION_KEY,a.refresh_token_enc),r=await fetch(TOKEN,{method:'POST',headers:{Authorization:'Basic '+btoa(e.PINTEREST_CLIENT_ID+':'+e.PINTEREST_CLIENT_SECRET),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:refresh,continuous_refresh:'true'})}),d=await r.json();if(!r.ok)throw Error(d.message||'Token refresh failed');await e.DB.prepare('UPDATE accounts SET access_token_enc=?,refresh_token_enc=?,access_token_expires_at=?,refresh_token_expires_at=?,updated_at=? WHERE id=?').bind(await enc(e.TOKEN_ENCRYPTION_KEY,d.access_token),d.refresh_token?await enc(e.TOKEN_ENCRYPTION_KEY,d.refresh_token):a.refresh_token_enc,now()+(d.expires_in||2592000),d.refresh_token_expires_at||null,now(),a.id).run();return d.access_token}
async function route(r,e){let u=new URL(r.url),p=u.pathname,m=r.method;if(p==='/'||p==='/index.html')return e.ASSETS.fetch(r);if(p==='/api/health')return json({ok:true});
if(p==='/api/accounts'&&m==='GET'){let x=await e.DB.prepare('SELECT id,name,pinterest_user_id,pinterest_username,status,connected_at FROM accounts ORDER BY id').all();return json({accounts:x.results})}
if(p==='/api/accounts'&&m==='POST'){let b=await r.json(),n=(await e.DB.prepare('SELECT COUNT(*) n FROM accounts').first()).n+1,id='pinterest_'+String(n).padStart(2,'0');await e.DB.prepare('INSERT INTO accounts(id,name,status,updated_at) VALUES(?,?,?,?)').bind(id,b.name||id,'disconnected',now()).run();return json({id})}
let bm=p.match(/^\/api\/accounts\/([^/]+)\/boards$/);if(bm&&m==='GET'){let a=await e.DB.prepare('SELECT * FROM accounts WHERE id=?').bind(bm[1]).first();if(!a)return json({error:'Account not found'},404);let d=await pf(await token(e,a),'/boards');return json({boards:(d.items||[]).map(x=>({id:x.id,name:x.name,privacy:x.privacy}))})}
if(p==='/api/oauth/start'&&m==='GET'){reqEnv(e);let id=u.searchParams.get('account_id'),a=await e.DB.prepare('SELECT id FROM accounts WHERE id=?').bind(id).first();if(!a)return json({error:'Account not found'},404);let state=uid();await e.DB.prepare('INSERT INTO oauth_states(state,account_id,created_at) VALUES(?,?,?)').bind(state,id,now()).run();let q=new URLSearchParams({client_id:e.PINTEREST_CLIENT_ID,redirect_uri:base(e)+'/api/oauth/callback',response_type:'code',scope:'user_accounts:read boards:read pins:read pins:write',state});return Response.redirect(OAUTH+'?'+q,302)}
if(p==='/api/oauth/callback'&&m==='GET'){reqEnv(e);let code=u.searchParams.get('code'),state=u.searchParams.get('state'),s=await e.DB.prepare('SELECT * FROM oauth_states WHERE state=?').bind(state).first();if(!s||s.created_at<now()-600)return json({error:'Invalid or expired OAuth state'},400);await e.DB.prepare('DELETE FROM oauth_states WHERE state=?').bind(state).run();let basic=btoa(e.PINTEREST_CLIENT_ID+':'+e.PINTEREST_CLIENT_SECRET),rr=await fetch(TOKEN,{method:'POST',headers:{Authorization:'Basic '+basic,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:base(e)+'/api/oauth/callback',continuous_refresh:'true'})}),d=await rr.json();if(!rr.ok)return json({error:d.message||'OAuth exchange failed'},400);let user=await pf(d.access_token,'/user_account');await e.DB.prepare(`UPDATE accounts SET pinterest_user_id=?,pinterest_username=?,status='connected',access_token_enc=?,refresh_token_enc=?,access_token_expires_at=?,refresh_token_expires_at=?,scopes=?,connected_at=?,updated_at=? WHERE id=?`).bind(String(user.id||''),user.username||'',await enc(e.TOKEN_ENCRYPTION_KEY,d.access_token),await enc(e.TOKEN_ENCRYPTION_KEY,d.refresh_token),now()+(d.expires_in||2592000),d.refresh_token_expires_at||null,d.scope||'',now(),now(),s.account_id).run();return Response.redirect(base(e)+'/?oauth=connected',302)}
if(p==='/api/imports'&&m==='GET'){let x=await e.DB.prepare('SELECT id,filename,row_count,approved_count,created_at FROM imports ORDER BY created_at DESC LIMIT 100').all();return json({imports:x.results})}
if(p==='/api/imports'&&m==='POST'){let b=await r.json(),rows=b.rows||[],clean=x=>String(x??'').trim(),find=(r,a)=>{for(let n of a){let k=Object.keys(r).find(k=>k.trim().toLowerCase()===n);if(k)return clean(r[k])}return ''};let id=uid(),valid=[];for(let r of rows){let account=find(r,['pinterest_account_id','account_id']),date=find(r,['publish_date','publish at','scheduled_at','date']),title=find(r,['title','pin_title']),image=find(r,['image_url','image','image link']);if(!account||!date||!title||!image)continue;if(!(await e.DB.prepare('SELECT id FROM accounts WHERE id=?').bind(account).first()))continue;let ts=Date.parse(date);if(Number.isNaN(ts))continue;valid.push({account,at:Math.floor(ts/1000),title,image,description:find(r,['description','pin_description']),link:find(r,['destination_url','url','link']),boardId:find(r,['board_id']),boardName:find(r,['board','board_name']),sectionId:find(r,['section_id']),sectionName:find(r,['section','section_name']),alt:find(r,['alt_text','alt'])})}if(!valid.length)return json({error:'No valid rows. Required: pinterest_account_id, publish_date, title, image_url'},400);let t=now();await e.DB.prepare('INSERT INTO imports(id,filename,account_ids,row_count,created_at) VALUES(?,?,?,?,?)').bind(id,b.filename||'upload.xlsx',JSON.stringify([...new Set(valid.map(x=>x.account))]),valid.length,t).run();for(let i=0;i<valid.length;i+=40){let batch=valid.slice(i,i+40).map(x=>e.DB.prepare(`INSERT INTO pins(id,import_id,account_id,publish_at,title,description,image_url,destination_url,board_id,board_name,section_id,section_name,alt_text,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'imported',?,?)`).bind(uid(),id,x.account,x.at,x.title,x.description,x.image,x.link,x.boardId,x.boardName,x.sectionId,x.sectionName,x.alt,t,t));await e.DB.batch(batch)}return json({import_id:id,row_count:valid.length})}
let im=p.match(/^\/api\/imports\/([^/]+)\/approve$/);if(im&&m==='POST'){let x=await e.DB.prepare("UPDATE pins SET status='approved',updated_at=? WHERE import_id=? AND status='imported'").bind(now(),im[1]).run();await e.DB.prepare('UPDATE imports SET approved_count=? WHERE id=?').bind(x.meta.changes||0,im[1]).run();return json({approved_count:x.meta.changes||0})}
if(p==='/api/queue'&&m==='GET'){let x=await e.DB.prepare("SELECT id,account_id,publish_at,title,status,last_error,pinterest_pin_id FROM pins WHERE status IN ('approved','publishing','published','failed','paused') ORDER BY publish_at LIMIT 500").all();return json({pins:x.results})}return json({error:'Not found'},404)}
async function publish(e){let q=await e.DB.prepare("SELECT p.*,a.status account_status FROM pins p JOIN accounts a ON a.id=p.account_id WHERE p.status='approved' AND p.publish_at<=? AND a.status='connected' ORDER BY p.publish_at LIMIT 10").bind(now()).all();for(let p of q.results){await e.DB.prepare("UPDATE pins SET status='publishing',attempts=attempts+1,updated_at=? WHERE id=? AND status='approved'").bind(now(),p.id).run();try{let a=await e.DB.prepare('SELECT * FROM accounts WHERE id=?').bind(p.account_id).first(),t=await token(e,a),body={title:p.title,description:p.description||undefined,link:p.destination_url||undefined,board_id:p.board_id||undefined,alt_text:p.alt_text||undefined,media_source:{source_type:'image_url',url:p.image_url,is_standard:true}},d=await pf(t,'/pins',{method:'POST',body:JSON.stringify(body)});await e.DB.prepare("UPDATE pins SET status='published',pinterest_pin_id=?,last_error=NULL,updated_at=? WHERE id=?").bind(d.id||null,now(),p.id).run()}catch(x){let auth=[401,403].includes(x.status);if(auth)await e.DB.prepare("UPDATE accounts SET status='error',updated_at=? WHERE id=?").bind(now(),p.account_id).run();await e.DB.prepare('UPDATE pins SET status=?,last_error=?,updated_at=? WHERE id=?').bind(auth?'paused':'failed',String(x.message).slice(0,1000),now(),p.id).run()}}}
export default{async fetch(r,e){try{return await route(r,e)}catch(x){return json({error:x.message||String(x)},500)}},async scheduled(ev,e,ctx){ctx.waitUntil(publish(e))}};
