name = "pinforge-pinterest-publisher"
main = "src/worker.js"
compatibility_date = "2026-09-01"

[vars]
APP_BASE_URL = "https://CHANGE-ME.example.com"

[[d1_databases]]
binding = "DB"
database_name = "pinforge-publisher-db"
database_id = "c5930581-7123-4518-80c8-bcac89d89fcb"

[triggers]
crons = ["* * * * *"]

[assets]
directory = "./public"
binding = "ASSETS"
